/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-11-26 15:49:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class app_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"webAppStyle.css\" />\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/a076d05399.js\"></script>\r\n");
      out.write("    <title>Web Application</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write(" \t\t");

		  if(session.getAttribute("username")==null){
			  response.sendRedirect("index.html");
		  }
	
		
      out.write("\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("      <div class=\"heading\">\r\n");
      out.write("        <i class=\"fas fa-bars icon\"></i>\r\n");
      out.write("        <h3 class=\"title_heading\">OBE Tool Application</h3>\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <nav class=\"side_navigation\">\r\n");
      out.write("      <ul class=\"list\">\r\n");
      out.write("        <li class=\"list_item\">\r\n");
      out.write("          <a href=\"#\" class=\"list_item-link\">\r\n");
      out.write("            <i class=\"fas fa-pencil-alt icon_list\"></i>\r\n");
      out.write("            Create Planner</a\r\n");
      out.write("          >\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"list_item\">\r\n");
      out.write("          <a href=\"#\" class=\"list_item-link\">\r\n");
      out.write("            <i class=\"far fa-newspaper icon_list\"></i>\r\n");
      out.write("            Generate Result\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"list_item\">\r\n");
      out.write("          <a href=\"#\" class=\"list_item-link\">\r\n");
      out.write("            <i class=\"fas fa-door-open icon_list\"></i>\r\n");
      out.write("            Log out\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("      <h1 class=\"heading_primary\">Assesment tool</h1>\r\n");
      out.write("      <div class=\"form_container\">\r\n");
      out.write("        <h2 class=\"heading_secondary\">Basic Information</h2>\r\n");
      out.write("        <form action=\"#\" method=\"GET\">\r\n");
      out.write("          <!-- Step 1 -->\r\n");
      out.write("          <div class=\"info\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <input name=\"NoOfStd\" type=\"text\" class=\"input_field\" placeholder=\"No of Students\" /\r\n");
      out.write("              required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <label class=\"label\">No of quizes</label>\r\n");
      out.write("              <select name=\"NoOfQu\" class=\"input_select\" required>\r\n");
      out.write("                <option value=\"1\">1</option>\r\n");
      out.write("                <option value=\"1\">2</option>\r\n");
      out.write("                <option value=\"1\">3</option>\r\n");
      out.write("                <option value=\"1\">4</option>\r\n");
      out.write("                <option value=\"1\">5</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <label class=\"label\">No of Assignments</label>\r\n");
      out.write("              <select name=\"NoOfAs\" class=\"input_select\" required>\r\n");
      out.write("                <option value=\"1\">1</option>\r\n");
      out.write("                <option value=2\">2</option>\r\n");
      out.write("                <option value=\"3\">3</option>\r\n");
      out.write("                <option value=\"4\">4</option>\r\n");
      out.write("                <option value=\"5\">5</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Step2 -->\r\n");
      out.write("          <div class=\"info\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <label class=\"label_question\"> Question&nbsp;1</label>\r\n");
      out.write("              <label class=\"label_question\"> Select Marks</label>\r\n");
      out.write("\r\n");
      out.write("              <select name=\"marks\" class=\"input_marks\" required >\r\n");
      out.write("                \r\n");
      out.write("                  <option value=\"1\">1</option>\r\n");
      out.write("                  <option value=\"2\">2</option>\r\n");
      out.write("                  <option value=\"3\">3</option>\r\n");
      out.write("                  <option value=\"4\">4</option>\r\n");
      out.write("                  <option value=\"5\">5</option>\r\n");
      out.write("                  <option value=\"6\">6</option>\r\n");
      out.write("                  <option value=\"7\">7</option>\r\n");
      out.write("                  <option value=\"8\">8</option>\r\n");
      out.write("                  <option value=\"9\">9</option>\r\n");
      out.write("                  <option value=\"10\">10</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <label class=\"label_question\">Select CLO</label>\r\n");
      out.write("                <select name=\"clo\" class=\"input_clo\" required>\r\n");
      out.write("                    <option value=\"1\">CLO1</option>\r\n");
      out.write("                    <option value=\"2\">CLO2</option>\r\n");
      out.write("                    <option value=\"3\">CLO3</option>\r\n");
      out.write("                    <option value=\"3\">CLO4</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <label class=\"label_question\"> Question&nbsp;1</label>\r\n");
      out.write("                <label class=\"label_question\"> Select Marks</label>\r\n");
      out.write("  \r\n");
      out.write("                <select name=\"marks\" class=\"input_marks\" required >\r\n");
      out.write("                  \r\n");
      out.write("                    <option value=\"1\">1</option>\r\n");
      out.write("                    <option value=\"2\">2</option>\r\n");
      out.write("                    <option value=\"3\">3</option>\r\n");
      out.write("                    <option value=\"4\">4</option>\r\n");
      out.write("                    <option value=\"5\">5</option>\r\n");
      out.write("                    <option value=\"6\">6</option>\r\n");
      out.write("                    <option value=\"7\">7</option>\r\n");
      out.write("                    <option value=\"8\">8</option>\r\n");
      out.write("                    <option value=\"9\">9</option>\r\n");
      out.write("                    <option value=\"10\">10</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                  <label class=\"label_question\">Select CLO</label>\r\n");
      out.write("                  <select name=\"clo\" class=\"input_clo\" required>\r\n");
      out.write("                      <option value=\"1\">CLO1</option>\r\n");
      out.write("                      <option value=\"2\">CLO2</option>\r\n");
      out.write("                      <option value=\"3\">CLO3</option>\r\n");
      out.write("                      <option value=\"3\">CLO4</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                  <label class=\"label_question\"> Question&nbsp;1</label>\r\n");
      out.write("                  <label class=\"label_question\"> Select Marks</label>\r\n");
      out.write("    \r\n");
      out.write("                  <select name=\"marks\" class=\"input_marks\" required >\r\n");
      out.write("                    \r\n");
      out.write("                      <option value=\"1\">1</option>\r\n");
      out.write("                      <option value=\"2\">2</option>\r\n");
      out.write("                      <option value=\"3\">3</option>\r\n");
      out.write("                      <option value=\"4\">4</option>\r\n");
      out.write("                      <option value=\"5\">5</option>\r\n");
      out.write("                      <option value=\"6\">6</option>\r\n");
      out.write("                      <option value=\"7\">7</option>\r\n");
      out.write("                      <option value=\"8\">8</option>\r\n");
      out.write("                      <option value=\"9\">9</option>\r\n");
      out.write("                      <option value=\"10\">10</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <label class=\"label_question\">Select CLO</label>\r\n");
      out.write("                    <select name=\"clo\" class=\"input_clo\" required>\r\n");
      out.write("                        <option value=\"1\">CLO1</option>\r\n");
      out.write("                        <option value=\"2\">CLO2</option>\r\n");
      out.write("                        <option value=\"3\">CLO3</option>\r\n");
      out.write("                        <option value=\"3\">CLO4</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <label class=\"label_question\"> Question&nbsp;1</label>\r\n");
      out.write("                    <label class=\"label_question\"> Select Marks</label>\r\n");
      out.write("      \r\n");
      out.write("                    <select name=\"marks\" class=\"input_marks\" required >\r\n");
      out.write("                      \r\n");
      out.write("                        <option value=\"1\">1</option>\r\n");
      out.write("                        <option value=\"2\">2</option>\r\n");
      out.write("                        <option value=\"3\">3</option>\r\n");
      out.write("                        <option value=\"4\">4</option>\r\n");
      out.write("                        <option value=\"5\">5</option>\r\n");
      out.write("                        <option value=\"6\">6</option>\r\n");
      out.write("                        <option value=\"7\">7</option>\r\n");
      out.write("                        <option value=\"8\">8</option>\r\n");
      out.write("                        <option value=\"9\">9</option>\r\n");
      out.write("                        <option value=\"10\">10</option>\r\n");
      out.write("                      </select>\r\n");
      out.write("                      <label class=\"label_question\">Select CLO</label>\r\n");
      out.write("                      <select name=\"clo\" class=\"input_clo\" required>\r\n");
      out.write("                          <option value=\"1\">CLO1</option>\r\n");
      out.write("                          <option value=\"2\">CLO2</option>\r\n");
      out.write("                          <option value=\"3\">CLO3</option>\r\n");
      out.write("                          <option value=\"3\">CLO4</option>\r\n");
      out.write("                      </select>\r\n");
      out.write("                  </div>\r\n");
      out.write("                   <div class=\"row\">\r\n");
      out.write("              <label class=\"label_question\"> Question&nbsp;1</label>\r\n");
      out.write("              <label class=\"label_question\"> Select Marks</label>\r\n");
      out.write("\r\n");
      out.write("              <select name=\"marks\" class=\"input_marks\" required >\r\n");
      out.write("                \r\n");
      out.write("                  <option value=\"1\">1</option>\r\n");
      out.write("                  <option value=\"2\">2</option>\r\n");
      out.write("                  <option value=\"3\">3</option>\r\n");
      out.write("                  <option value=\"4\">4</option>\r\n");
      out.write("                  <option value=\"5\">5</option>\r\n");
      out.write("                  <option value=\"6\">6</option>\r\n");
      out.write("                  <option value=\"7\">7</option>\r\n");
      out.write("                  <option value=\"8\">8</option>\r\n");
      out.write("                  <option value=\"9\">9</option>\r\n");
      out.write("                  <option value=\"10\">10</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <label class=\"label_question\">Select CLO</label>\r\n");
      out.write("                <select name=\"clo\" class=\"input_clo\" required>\r\n");
      out.write("                    <option value=\"1\">CLO1</option>\r\n");
      out.write("                    <option value=\"2\">CLO2</option>\r\n");
      out.write("                    <option value=\"3\">CLO3</option>\r\n");
      out.write("                    <option value=\"3\">CLO4</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Step 3 -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Step 4 -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Step 5 -->\r\n");
      out.write("\r\n");
      out.write("          <!-- Buttons -->\r\n");
      out.write("          <div class=\"btn_row\">\r\n");
      out.write("            <input type=\"button\" value=\"Previous\" class=\"btn btn_pre\" onclick=\"pre()\" />\r\n");
      out.write("            <input type=\"button\" value=\"Next\" class=\"btn btn_next\" onclick=\"next()\"/>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"webAppScript.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
